defaults:
  deploy_cmd: gem push brew-gem*.gem
  before_deploy_cmds:
    - /usr/local/bin/op tag-release
    - sed -i "" -e "s/\".*/\"$(git tag | grep '^v' | sort -n -t. -k1,1 -k2,2 -k3,3 | tail -1 | sed s/v//)\"/" lib/brew/gem/version.rb
    - git add lib/brew/gem/version.rb
    - git commit -m "Version Bump" && git push
    - gem build brew-gem.gemspec
  after_deploy_cmds:
    - rm *.gem
environments:
  -
    rubygems: {}
